import SwiftUI

struct PaywallView: View {
    private let includedFeatures = [
        "AI coaching workflows included in this release",
        "Job description scanner and supporting statement drafts",
        "Voice practice with editable speech-to-text transcripts",
        "Mock interview, STAR builder, NHS values coach, and analytics",
        "PDF export, application tracking, and share cards"
    ]

    var body: some View {
        PremiumScreen {
            ScrollView {
                VStack(alignment: .leading, spacing: 18) {
                    hero
                    includedAccessCard
                    privacyCard
                }
                .padding(20)
            }
        }
        .navigationTitle("Access")
        .premiumNavigationTitleStyle()
    }

    private var hero: some View {
        VStack(alignment: .leading, spacing: 16) {
            Text("Included in this build")
                .font(.caption.weight(.bold))
                .foregroundStyle(CareerCoachTheme.gold)
                .textCase(.uppercase)

            Text("Premium preparation tools, no purchase required.")
                .font(.system(.largeTitle, design: .rounded).weight(.black))
                .foregroundStyle(CareerCoachTheme.textPrimary)
                .fixedSize(horizontal: false, vertical: true)

            Text("This submitted version does not sell digital purchases. All visible coaching workflows are available for App Review and user evaluation.")
                .font(.subheadline)
                .foregroundStyle(CareerCoachTheme.textSecondary)
                .fixedSize(horizontal: false, vertical: true)
        }
        .premiumCard(cornerRadius: 28, padding: 22)
    }

    private var includedAccessCard: some View {
        PremiumDashboardCard(title: "Career coaching access", subtitle: "No purchase is required in this release.", systemImage: "checkmark.seal.fill", accent: CareerCoachTheme.mint) {
            VStack(alignment: .leading, spacing: 9) {
                ForEach(includedFeatures, id: \.self) { feature in
                    Label(feature, systemImage: "checkmark.circle.fill")
                        .font(.subheadline)
                        .foregroundStyle(CareerCoachTheme.textSecondary)
                        .fixedSize(horizontal: false, vertical: true)
                }
            }
        }
    }

    private var privacyCard: some View {
        PremiumDashboardCard(title: "AI data handling", subtitle: "Local-first coaching for this release.", systemImage: "lock.shield.fill", accent: CareerCoachTheme.electricBlue) {
            VStack(alignment: .leading, spacing: 10) {
                Text("The default AI coaching responses are generated by the app's local coaching service. Job descriptions, supporting statement notes, interview answers, and voice transcripts are not sent to a developer-operated server or a third-party AI provider in this build.")
                    .font(.subheadline)
                    .foregroundStyle(CareerCoachTheme.textSecondary)
                    .fixedSize(horizontal: false, vertical: true)

                Text("Speech-to-text uses Apple's system speech recognition permission when the user chooses voice input.")
                    .font(.caption)
                    .foregroundStyle(CareerCoachTheme.textTertiary)
                    .fixedSize(horizontal: false, vertical: true)
            }
        }
    }
}
